<?php

$en =array(
    '__pageTitleHomepage__' => 'Homepage',
    '__pageTitleFaq__'      => 'F.A.Q.',
    '__pageTitleT&C__'      => 'Terms & Conditions',
    '__pageTitleT&C2__'      => 'Terms & Conditions',
    '__callUs__'            => '客服热线',
    '__menuProcesses__'     => 'How it works?',
    '__menuFAQ__'           => 'FAQ',
    '__menuHomecredit__'    => 'About HCC',
    '__menuCalculator__'    => 'Borrow now!',
    '__textTop__'           => '福袋<span style="color:#ffdc00">百里挑一</span>送幸运金！<br>让你只借不还',
    '__textBottom__'        => '年轻人喜欢的贷款方式',
    '__calculatorTitle__'   => 'Fudai calculator',
    '__calculatorDesc__'    => 'Calculate your monthly repayment',
    '__stripOne__'          => 'Please choose your loan amount',
    '__stripTwo__'          => 'Please choose your tenure',
    '__month__'             => 'month',
    '__months__'            => 'months',
    '__monthPayment__'      => 'Your monthly repayment is',
    '__loanButton__'        => 'Borrow now',
    '__customerService__'   => 'If you have any questions, Please call our customer service line 400 027 1265, or',
    '__clickHere__'         => 'click here to see the terms of use',
    '__customService2__'    => 'Fudai is a product only for new HCC customers, existing customers should apply for our other products.',
    '__dot1Title__'         => 'Low monthly fee',
    '__dot1Desc__'          => '1.5% monthly fee rate',
    '__dot2Title__'         => 'Fast speed',
    '__dot2Desc__'          => '5 mins online approval',
    '__dot3Title__'         => 'More benefits',
    '__dot3Desc__'          => '15 days free early repayment, no other fees required.',
    '__processHeader__'     => '4 easy steps to&nbsp;get&nbsp;Fudai easily',
    '__processDesc__'       => 'Here it is, Fudai helps you to get money, it’s not magic',
    '__process1Header1__'   => 'Step 1',
    '__process1Header2__'   => 'customize your&nbsp;fudai',
    '__process1Desc__'      => 'Choose loan amount and tenure in the calculator, you will see the monthly repayment amount. Then click the button to go to the next step!',
    '__process2Header1__'   => 'Step 2',
    '__process2Header2__'   => 'submit your “fudai&nbsp;wish”',
    '__process2Desc__'      => 'Fill out your loan application and finish SMS verification then submit your loan application. Now, the lucky bag full of cash is only one step away!',
    '__process3Header1__'   => 'Step 3',
    '__process3Header2__'   => 'wait for fudai to&nbsp;come',
    '__process3Desc__'      => 'Wait for 5 mins! Then you will know the result of your application. If it’s approved, the cash will fly to your bank account right away.',
    '__process4Header1__'   => 'Step 4',
    '__process4Header2__'   => 'repay by direct debit',
    '__process4Desc__'      => 'Bind your debit card account, even if you tend to forget things, the repayment can be done automatically by direct debit in time!
* To avoid default, Please try to make sure that your debit card has enough money on the account.',
    '__processButton__'     => 'Borrow now',
    '__propHeader__'        => 'Is Fudai right for me?',
    '__propDesc__'          => 'If you fit in following characteristics, then congratulations, the lucky bag is right for you!',
    '__prop1__'             => 'Need extra cash in a short time for consumption purpose',
    '__prop2__'             => 'Hate to fill in complicated forms',
    '__prop3__'             => 'Don’t want to pay high fees',
    '__faqHeader__'         => 'Choose your question',
    '__faq1Header__'        => '1. What is HCC Mini Cash Loan?',
    '__faq1Desc__'          => 'Mini Cash Loan is a new small cash loan by HCC which enables you to borrow small amounts of money up to 500 RMB. Repayment is done over a period of up to 6 months in equal monthly installments.',
    '__faq2Header__'        => '2. Who is HCC?',
    '__faq2Desc__'          => 'HCC is abbreviation for Home Credit China, which is a leading consumer finance company with 10+ years’ experience in China. It’s the only foreign owned CFC among the first four granted with CFC license by CBRC. For more information of HCC, you can refer to our <a href="http://www.homecreditcfc.cn" target="_blank">official website</a>.',
    '__faq3Header__'        => '3. What’s the price of HCC Mini CashLoan?',
    '__faq3Desc__'          => 'Monthly service fee is 1.5% of the loan amount. No others fees are charged.',
    '__faq4Header__'        => '4. When should I repay?',
    '__faq4Desc__'          => 'Your first repayment day is 25 days after your approval date and the following due dates will be the same date. If your application date is 28th-31st of the month, your repayment date would be 1st of the following month.<br><br>
    When your loan is approved, you will see your first due date on the summary page. We will also send you email notification with your due date and repayment details included. And this information is also available on our Customer Portal.',
    '__faq5Header__'        => '5. How to repay?',
    '__faq5Desc__'          => 'Repayment method for HCC Mini Cash Loan is Direct Debit. Just put the money on your bank card and the repayment will be done automatically every month. Here is the list of banks that support Direct Debit for us. For special cases Please refer to <a href="index.php?page=terms2&lang=en" target="_blank">T&C</a>.',
    '__faq6Header__'        => '6. How to check my HCC Mini Cash Loan status?',
    '__faq6Desc__'          => 'To check your Mini Cash Loan status, you can log in to <a href="https://wode.homecredit.cn/CustomerService/login" target="_blank">Customer Portal</a> on HCC website to check your basic info and contract details.  ',
    '__faq7Header__'        => '7. What if I cannot repay in time, will I be charged with penalty?',
    '__faq7Desc__'          => 'Penalty is charged if customer fails to repay the loan on the due date. The penalty fee structure is as below.',
    '__faq7Bottom__'        => 'We advise you to cherish your credit record by repaying the loan on time as it may have negative impact to your future borrowings if there’s default. If you have any problem with repaying the loan or any inquiries you can call our customer service hotline 400 027 1262.',
    '__faq8Header__'        => '8. Someone from HCC called me. Is my private information safe?',
    '__faq8Desc__'          => 'HCC performs welcome call to each and every customer after your Mini Cash Loan application is approved, the purpose is verify your application information and make sure that you are aware of the details of your Mini Cash Loan service. We keep your private information strictly confidential.',
    '__faq9Header__'        => '9. Does HC perform verification?',
    '__faq9Desc__'          => 'Yes, HC performs real time online verification of each loan application. ',
    '__faq10Header__'        => '10. Why I was not approved?',
    '__faq10Desc__'          => 'It could be because you input wrong information; your information (ID, phone number, bank card) is not matching or you are not eligible for this amount. Your eligibility is regularly updated; we advise you to keep a good credit record and try to apply next time.',
    '__faq11Header__'        => '11. How can I apply for early repayment?',
    '__faq11Desc__'          => 'If you would like to apply for early repayment, Please call HCC customer service at 4000271262. We will process your request free of charge.',
    '__faq12Header__'        => '12. What are HC general terms and conditions for Mini Cash Loan?',
    '__faq12Desc__'          => '1. The number of instalments, amount and due dates of each drawdown are stated in the application form of that drawdown. You shall make repayment in full on each due date on schedule. The monthly instalment as stated on the application form is the total amount payable for that drawdown each month, including loan principal, interest, loan administration fee, customer service fee, handling fee (if any) ,flexibility package fee (if any), etc.. If you have more drawdowns under this Contract at the same time, then the total repayment amount shall be the sum of monthly instalments of all such drawdowns. Please make sure the amount in your bank account before the due date (including the due date) of each month is sufficient to cover the monthly instalment.<br><br>'
    . '2. If you decide to cancel the drawdown applied via HCC Gateway, you can repay the full loan amount of each drawdown within the cool-off period of first 30 days from applying for that drawdown without incurring any additional charges or penalties. If you change your mind after 30 days, you can still repay any drawdown but you will need to pay interest and fees on top of the full loan amount of that drawdown. Make sure to check your contract to fully understand how to apply for such early repayment and what you will be required to pay.<br><br>'
    . '3. You can make applications under the Contract by using convenient service channels (such as HCC Gateway, online customer portal, telephone hotline or app etc.) or at POS anytime. You need to identify yourself with the agreed identification factor (such as password etc.) while making applications through convenient service channels and you must use the convenient service channels strictly according to the stipulations of the Contract. Any use of your identification factor on convenient service channels will result in your liability, no matter who used or abused your identification factor. You must keep your identification factor safe and confidential and use it only in safe environment. If your identification factor is lost, stolen or otherwise compromised, you must let us know immediately and change the settings of your identification factor to avoid your liabilities arising from the use of compromised identification factor.<br><br>'
    . '4. You can use the loan only for the purpose agreed in the Contract. You must retain a proof that you used the loan for such purpose (such proof may include consumption invoices, contracts, etc.). You must provide such proof to us if we ask you. <br><br>'
    . '5. Your personal information is used to inquire from and input into personal credit information databases, for the purposes of performing your contract, for protection and enforcement of our rights or to contact you for credit assessment, data processing, risk control, advertising, late payment collection and similar purposes. We may engage other companies for the above purposes and we will provide your personal information and your credit information to such our outsourcing partners if necessary. <br><br>'
    . '6. You must inform us of the change of your personal information (e.g. mobile phone number), address or employer. <br><br>'
    . '7. Any dispute between you and us shall be resolved by friendly consultation. If consultation cannot resolve the dispute, each party may initiate a legal action in a court of the place where the contract is concluded. (Please view the stipulations on the signing place in the bottom left of the Consumer Finance Loan Contact, Terms & Conditions.)<br><br>'
    . '8. If you do not pay any amount when it is due according to your contract, you will be charged late fee for each drawdown applied via HCC Gateway (30 RMB for 10 days delay, 80 RMB for 30 days delay, 130 RMB for 60 days delay and 130 RMB for 90 days delay). If the loan principle of each drawdown is less than 1000 RMB, the late fee will be charged by half of the abovementioned rate. If you are late with payments, under specific circumstances described in the contract you may lose the benefit of instalments and in such case you will have to pay all amounts under your contract in one lump sum. Also we will report your failure to pay on time to the relevant credit databases. We may also approach other people who know you and ask them for help with reminding you to pay the overdue amounts. If you have default of repayment, we can select to pay the amount payable by you to the Customer Service Provider on behalf of you and may claim for such amount by means of litigation etc.<br><br>'
    . '9. You agree that we can use phone recording and the Institutional Parties’ computer system logs as sufficient evidence determining the contents of our agreement for any potential dispute with respect to that drawdown.<br><br>'
    . '10. If you cancel your purchase order or return the Product to the Merchant within 30 days from applying for the drawdown via HCC Gateway, the drawdown will be cancelled and we will return to you in full all monthly installment amounts you already paid under that drawdown. If you cancel your purchase order or return the Product to the Merchant after 30 days from applying for the drawdown via HCC Gateway, we will return to you only the principal amount already paid by you as part of monthly installment. If you have other unpaid amounts due, we will settle them with the money otherwise payable to you.<br><br>'
    . '11. The above text is for your information only and in terms of specific matters the Contract shall prevail. Please read carefully the full text of your Contract and other documents in relation to the loan to understand all your rights and obligations in detail.',
    '__faq13Header__'        => '13. What is HC privacy policy?',
    '__faq13Desc__'          => 'Home Credit (hereinafter referred to as “we”) respects and protects customers’ personal information. We apply various and reasonable physical, electronic and management security measures to protect your information and prevent it from being leaked, destroyed or lost, including but not limited to SSL, encrypted information storage and data center access right control. We have strict management over the employees or outsourced staff who might have access to your information, including but not limited to different levels of access right control according to their position, signing NDA with them and monitor their operation etc. ',
    '__top2__'              => '10-29 days over due',
    '__top3__'              => '30-59 days over due',
    '__top4__'              => '60-89 days over due',
    '__top5__'              => 'More than 90 days over due',
    '__bottom1__'           => 'Loan amount <=1000 RMB',
    '__bottom2__'           => '15',
    '__bottom3__'           => '55',
    '__bottom4__'           => '120',
    '__bottom5__'           => '185',
    '__faqButton__'        => 'get fudai now',
    '__termsHeader__'       => 'Terms of Use regarding HCC Gateway',
    '__termsP1__'           => 'Terms of Use regarding HCC Gateway (hereinafter referred to as “Terms of Use”) refers to a valid agreement concluded between Home Credit Consumer Finance Co., Ltd. (hereinafter referred to as “Lender”) and Shenzhen Home Credit Financial Services Co., Ltd. (collectively referred to as the “Institutional Parties”) and HCC customers (hereinafter referred to as “Customer” or “You”) regarding the relevant issues such as use of services as provided by HCC Gateway (hereinafter referred to as “Service”) etc.. The acceptance of the Terms of Use through click-signing on the website or other means by Customer means that Customer has reached an agreement with the Institutional Parties and agreed to accept the whole content of the Terms of Use.',
    '__termsP2__'           => 'Before accepting this Terms of Use, Please read the whole content of the Terms of Use (particularly the underlined and bold-faced content) carefully. If You don´t accept any content of the Terms of Use, or can´t understand the interpretation of the stipulations by the Institutional Parties accurately, Please don´t proceed any further. Your continuation in use of HCC Gateway will be considered as your acceptance of these Terms of Use.',
    '__termsH1__'           => 'Customer Duties',
    '__termP3__'            => 'You hereby irrevocably agree that any transaction by using your identity authentication factor including but not limited to account registered with the Merchant by You, password, dynamic password to log into the Merchant´s website or APP and choosing HCC loans as payment method to be redirected to HCC Gateway shall be deemed as conducted by You. You agree to bear results incurred and shall be liable for all damages, obligations and payments arising from the use of your identity authentication factor irrespective of who actually used it.',
    '__termP4__'            => 'You shall keep all information required for conducting transactions on HCC Gateway such as your account registered with the Merchant, password, dynamic password etc. safe. If your identity authentication factor is lost, stolen or suspected to be known to or misused by a third party and it could result in the decrease in safety of your use of HCC Gateway and Service available to You on HCC Gateway, You shall be obligated to immediately report to the Institutional Parties so that the Institutional Parties can take appropriate measures as necessary in time and reduce losses which are likely to occur. You agree to bear all losses and liabilities incurred when failing to fulfill the aforementioned obligations in a timely manner.',
    '__termP5__'            => 'While applying for HCC loans on HCC Gateway, You shall fill in the items as listed in the application form according to requirements and insert the dynamic password as provided by the Institutional Parties or any third party as authorized by the Institutional Parties by means of SMS upon submitting the application form successfully. Upon verifying your identity by the Institutional Parties, You need to submit authorization letter online to complete your application. The Institutional Parties will then inform You on whether or not to approve your application timely through HCC Gateway. You acknowledge and consent that click-signing the application will be deemed as confirmation on the conditions Customer shall satisfy as required by the Lender for providing HCC loans (including the loan principal under this application, interests, fees, number of monthly payments, monthly installment as well as other terms and conditions). No written form is required. In the meanwhile, your confirmation shall be a supplement or an amendment to the Consumer Finance Loan Contract already or to be concluded between You and the Institutional Parties and constitute an integral part thereof. You shall bear all liabilities for the genuineness and validity of transactions during the utilization of the Service. You undertake that you will bear on your own all risks incurred by any transactions conducted by the Institutional Parties as requested by You.',
    '__termsH2__'           => 'Customer Authorizations',
    '__termP6__'            => 'You acknowledge that the application data, transaction data etc. on the HCC Gateway shall be subject to the record in the back office system of the Institutional Parties. In the Meanwhile, You authorize the Institutional Parties to take following actions:',
    '__termP7__'            => 'out of the need for providing the loan, to provide your personal information and related loan information to domestic affiliated companies and business partners involved in the consumer finance business, includes but not limited to processing loan applications, managing  all stages of the loan, managing accounts and payments, protection and enforcement of rights etc.；',
    '__termP8__'            => 'to outsource part of the services related to the Consumer Finance Loan Contract to their business partners and provide your related personal information to such partners in this respect；',
    '__termP9__'            => 'out of the need for providing the loan, to enquire and obtain your related personal information (including but not limited to the Borrower’s identity information, social security information and housing fund information, etc.) from the Lender’s domestic affiliated companies and business partners and other lawful available sources；',
    '__termP10__'           => 'To obtain all details and information/data concerning You which are available in any third party irrespective whether You have given your consent to such third party to share such your data with any third person. You hereby authorize all parties in lawful possession of data about You (without limitation) to provide information/data or enable access to their data and to share such data with the Institutional Parties for the purposes of evaluation of your credit status and for other purposes related to the issuance/repayment/enforcement of the loan;',
    '__termP11__'           => 'to store carefully relevant information filled in on the HCC Gateway, your personal information, personal credit reporting information and relevant documents in order to keep providing services to You accordingly including but not limited to using the afore mentioned information for promoting and providing other products or services. To take advantage of your personal information to recommend products, including sending commercial advertisement to your postal address, e-mail address, mobile phone, QQ, Wechat, APP etc., which shall still be effective after the Consumer Finance Loan Contract expires',
    '__termP12__'           => 'To exchange personal and credit information with the merchants and other third parties in relation to processing payment for your purchase of Products with the loans as provided under the Consumer Finance Loan Contract;',
    '__termP13__'           => 'You agree and authorize the Institutional Parties at their own discretion to take corresponding measures against accounts on the Customer Portal which are suspected of fraud or are controlled by a third party for the purpose of fraud on their own or through any third party. The afore mentioned measures include but are not limited to the  freezing of accounts and funds, disposal of funds suspected of fraud etc.',
    '__termsH3__'           => 'Legal Liability and Disclaimer',       
    '__termP14__'             => 'If any of the following circumstances occurs, the Institutional Parties shall be entitled to immediately terminating the availability of the Service on HCC Gateway to You without bearing any liabilities: ',
    '__termP15__'           => '(1) Breach of the Consumer Finance Loan Contract or the Terms of Use agreed by You;<br> 
(2) The Service is used for any illegal purpose or purpose of breaching the Terms of Use;<br>
(3) Violating the amendment and/or supplementary agreement, relevant business rules etc. published occasionally by the Institutional Parties through POS, website or convenient service channels;<br>
(4) The Institutional Parties think the Service provided to You involves risk.',  
    '__termP16__'           => 'The Institutional Parties shall not bear any loss of customer arising from communication line fault, technology problems, network or computer breakdown, instability of system and any other Force Majeure.',
    '__termP17__'           => 'The Institutional Parties have the right to terminate your access to HCC Gateway without notice or explaining the reason.',
    '__termP18__'           => 'The Institutional Parties do not guarantee availability of HCC Gateway or all the functions at all times to all customers.',
    '__termsH4__'           => 'Applicable Law and Dispute Settlement',  
    '__termP19__'           => 'You agree that the Chinese law shall apply to the Terms of Use. Any dispute concerning the execution, implementation or interpretation of the Terms of Use shall be resolved by negotiation. If negotiation cannot resolve the dispute, both Parties agree to use the stipulations regarding dispute resolution in the Consumer Finance Loan Contract signed between You and the Institutional Parties to handle the conflict or dispute.',
    '__termsH5__'           => 'Miscellaneous',
    '__termP20a__'           => 'The Terms of Use includes the main content and all business rules on HCC Gateway Service already published or to be published in future. All business rules shall constitute an integral part of the Terms of Use and have the same legal effect. The Institutional Parties shall be entitled to unilaterally revising or amending the content aperiodically and publishing the amended Terms of Use through the Institutional Parties´ POS and/or website (',
    '__termP20Lang__'       => 'en',
    '__termP20b__'          => '). A separate notice is not needed. Any revision or amendment to the Terms of Use shall become effective upon publication. If You continue to use this Service after the content of Terms of Use has been amended, it shall be deemed as acceptance of the newly amended content of Terms of Use by You. Otherwise You must stop using this Service immediately.',
    '__termP21__'           => 'If there are any issues which are not stipulated in the Terms of Use or there are any conflicts with the stipulations of the Consumer Finance Loan Contract, the Consumer Finance Loan Contract signed between You and the Institutional Parties shall prevail.',        
    '__terms2Header__'      => 'Consumer Finance Loan Contract, Terms & Conditions',
    '__terms2H1__'          => 'Whereas:',
    '__terms2P1__'          => '(1) Home Credit Consumer Finance Co., Ltd. (the “Lender”) is a consumer finance company authorized to extend personal consumer loans pursuant to the Pilot Administrative Measures for Consumer Finance Companies; and',
    '__terms2P2__'          => '(2) The natural person (the “Borrower”) who signed or agreed these Terms & Conditions online intends to obtain, once or multiply, from the Lender a loan (POS loan or Cash loan, as described on the Consumer Finance Loan Application Form, hereinafter as “Application Form” which together with these Terms & Conditions forms and is referred to as the “Contract”. POS loan is for the purpose of purchasing the goods and/or services (the “Product”) from a merchant (the “Merchant”) as described on the Application Form; Cash loan is for the purpose of consumption as described on the Application Form) and whereby Shenzhen Home Credit Financial Services Co., Ltd. (the “Customer Service Provider”) will provide customer services to the Borrower in relation to the loan;',
    '__terms2P3__'          => 'the Lender, Customer Service Provider (collectively referred to as the “Institutional Parties”) and the Borrower agree as follows:',
    '__terms2H2__'          => '1. BASIC LOAN TERMS & DEFINITIONS',
    '__terms2P4__'          => '1.1 The loan principal is as stated on each one of the Application Forms relating to the respective drawdown. The down payment payable by the Borrower himself to the Merchant (i.e. the down payment amount stated on the Application Form) is not included in the loan principal while applying for POS loan.',
    '__terms2P5__'          => '1.2 The monthly interest rate applicable to the loan is the “monthly interest rate” stated on each one of the Application Forms relating to the respective drawdown.',
    '__terms2P6__'          => '1.3 The loan is payable in equal monthly installments. The number of installments required to fully repay the loan under each drawdown and the RMB amount per installment (including the Borrower’s other payment obligations hereunder relating to each drawdown, excluding late fees) are stated on each one of the Application Forms relating to the respective drawdown as “number of monthly payments” and “monthly installment.”',
    '__terms2P7__'          => '1.4 The loan period for each drawdown shall commence from the date on which the Borrower signs or submits through the convenient service channels or authorizes Customer Service Provider to submit the Application Form relating to the respective drawdown and end on the date the last installment for the respective drawdown becomes due. For avoidance of confusion, if the Borrower owes any amounts due hereunder as of the end of the loan period, such debts are not automatically discharged by the ending of the loan period.',
    '__terms2P8__'          => '1.5 The date on which the first installment of the first drawdown under this Contract is due is the “first due date” stated on the Application Form for the first drawdown. After the first installment, each subsequent installment (including each installment of other drawdowns under the Contract, if any) is due on the same day of each calendar month, stated on the Application Form for the first drawdown  (together with the first due date, the “due dates”).',
    '__terms2P9__'          => '1.6 The Borrower hereby irrevocably authorizes the Lender to disburse the loan principal to the Merchant as payment for the Product in case of a POS loan or directly disburse the loan principal to the bank account as designated by the Customer in each one of the Application Forms relating to the respective drawdown in case of a cash loan.',
    '__terms2P10__'         => '1.7 Loan purpose: only be used for the loan purpose as stated in each one of the Application Forms relating to the respective cash loan. If the use of the loan by the Borrower fails to comply with the loan purpose, the Lender may proceed according to Section 12 of this Contract, and the Borrower shall pay RMB 200 as contract penalty upon request of the Lender.',    
    '__terms2H3__'          => '2. APPLICATION PROCESS',
    '__terms2P11__'         => '2.1 The Borrower can make application for a drawdown through convenient service channels or at POS any time; however, the Lender may decide at its own discretion to approve or reject the Borrower’s application for additional drawdown.',
    '__terms2P12__'         => '2.2 Each time when the Borrower wishes to make a drawdown, the Borrower shall deliver an Application Form for the drawdown through convenient service channels or at POS. The Application form relating to such drawdown, together with this Terms and Conditions, shall govern the drawdown which shall be a part of the Contract.<br>
    The Institutional Parties and the Borrower irrevocably agree, If the Borrower applies for a drawdown through convenient service channels, the Borrower shall use convenient service channels to confirm his/her agreement with the terms on which such drawdown is made available by the Lender (including confirmation of additional loan amount and related interest, fees, loan period, new total amount of monthly installment and other terms and conditions specified by the Institutional Parties).. Institutional Parties and Borrower explicitly agree that such confirmation will not be made in writing (except the circumstance under which the Institutional Parties provide sign-at-door service). Such Borrower’s confirmation shall serve as its amendment where applicable and constitute an integral part of this Contract. The Application Form or other documents signed by Borrower when applying for a drawdown at POS or when the Institutional Parties provide sign-at-door service shall serve the same purpose.',
    '__terms2P13__'         => '2.3 The Borrower further agrees that if the Borrower has several drawdowns in parallel under this Contract, then the total monthly installment amount under this Contract includes the monthly installments of such drawdowns. It’s the Borrower’s obligation to pay the total monthly installment amount on schedule. However, for the Borrower’s convenience, the Institutional Parties will inform the Borrower of the total monthly installment amount payable on the upcoming due date at least 5 days prior to each due date through the convenient service channels. Irrespective of whether the Borrower has received the notification from the Institutional Parties, it remains the Borrower’s obligation to repay the total monthly installment amount in full.',
    '__terms2P14__'         => '2.4 If the Borrower submits through the online customer portal or authorizes the Institutional Parties to submit an application for a drawdown on his/her behalf, the Borrower shall log into the online customer portal and/or APP and confirm the terms of applied drawdown within a deadline as informed by the Institutional Parties, which begins on the date when the application for this drawdown is submitted (except the circumstance under which the Institutional Parties provide sign-at-door service). If the Borrower fails to complete or confirm the application within the deadline as informed each time by the Institutional Parties for whatever reason, the application will become invalid automatically.',
    '__terms2P15__'         => '2.5 In case any drawdown application completed through convenient service channel is determined invalid or without having the effect envisaged by the Contract, the Borrower and the Institutional Parties agree to use phone recording and the Institutional Parties’ computer system logs as sufficient evidence determining the contents of their agreement for any potential dispute with respect to that drawdown. In absence of the above evidence, with respect to that drawdown, the content in the Application Form and these Terms & Conditions which have been signed by the Borrower at POS (in particular the determination of interest, fees and due dates etc.) shall apply mutatis mutandis. ',
    '__terms2H4__'          => '3. LOAN ADMINISTRATION SERVICES',
    '__terms2P16__'         => '3.1 In relation to each drawdown under the Contract, the Lender provides the following services to the Borrower:<br>'
    . '(1) General consumer finance consulting;<br>'
    . '(2) Loan proposal design;<br>'
    . '(3) Personal credit management & maintenance;<br>'
    . '(4) Document preparation;<br>'
    . '(5) Paid on behalf handling (free of charge);<br>'
    . '(6) Account application (free of charge); and<br>'
    . '(7) Consultation, sales & service point maintenance.<br>',
    '__terms2P17__'         => '3.2 In consideration for the above services, the Borrower shall pay a fee (the “loan administration fee”), which is charged every month during the loan period and forms a part of the monthly installments. Each abovementioned service (excluding free service) rate is 1/5 of the loan administration fee rate, and the loan administration fee rate is stated as “monthly loan administration fee rate” on each one of the Application Forms relating to the respective drawdown.',
    '__terms2H5__'          => '4. PARTICIPATION IN INSURANCE',
    '__terms2P18__'         => '4.1 If the Borrower elects to participate in insurance on the Application Form relating to a specific drawdown, he/she consents to be enrolled as an “insured party” in the insurance contract as stated in the Application Form relating to that drawdown where the beneficiaries are the Lender and the Customer Service Provider (both beneficiaries are entitled to 100% of the insurance proceeds) and the insured amount is 110% of the entire loan principal of that drawdown. Any pay-out under the policy will be credited toward the Borrower’s debt owed to the Lender and Customer Service Provider. The amount of insurance pay-out exceeding the Borrower’s all outstanding debt will be paid to the Borrower or his/her family.',
    '__terms2P19__'         => '4.2 Upon Borrower’s election to participate in insurance, the Lender or the Customer Service Provider as may be the case has sole discretion whether or not to approve and enroll the Borrower in the insurance contract.',
    '__terms2P20__'         => '4.3 If the Borrower is enrolled in the insurance contract, the Borrower shall pay the Institutional Party which is the policyholder as the case may be a fee for the cost of administration incurred therefrom (the “handling fee”).  Such handling fee forms part of the monthly installment and is “monthly handling fee” amount stated on each Application Form. If a Borrower has multiple drawdowns for which he participates in insurance contracts, the handling fee shall be paid separately for each drawdown, and the total monthly handling fee will change accordingly.',
    '__terms2P21__'         => '4.4 After the Borrower is enrolled in the insurance contract, the Institutional Party which is the policyholder as the case may be reserves the right, at its sole discretion, to withdraw the Borrower from the insurance contract for some or all drawdowns hereunder upon the Borrower’s request or for any other reason, such as upon the termination of the insurance contract itself between the such Institutional Party and insurance company or upon discovery that the Borrower made misrepresentation regarding his/her health status. In such event, the Borrower does not need to pay the handling fee as part of future monthly installments.',
    '__terms2H6__'          => '5. FLEXIBILITY PACKAGE',
    '__terms2P22__'         => '5.1<br>'
    . '(1) The Borrower may select to purchase the Flexibility Package for any drawdown. Flexibility Package includes Payment Holiday, Change of Due Date and Free Early Repayment. The price for purchasing Flexibility Package by the Borrower (the “Flexibility Package Fee”) shall be paid to the Lender each month and forms part of the monthly installments and is stated by the “Monthly Flexibility Package Fee” on the Application Form of such drawdown. In case that the charging standards of the Flexibility Package Fee are changed later, the Flexibility Package Fee for existing drawdowns shall still be paid based on the original standard.<br>'
    . '(2) In case that the Borrower has overlapping drawdowns under this Contract and two or more Flexibility Package Fees payable on a single due date, then the Borrower shall only need to pay the lowest amount of Flexibility Package Fee payable on that single due date, (which shall not be affected by the preferential product as stipulated in Section 13 of these Terms & Conditions). An overlapping drawdown as stipulated under this Contract refers to a drawdown which shares at least the same one due date with other one or more drawdowns. In case for a drawdown Payment Holiday or Change of Due Date is applied or a drawdown is early repaid by the Borrower (including Free Early Repayment, but excluding early repayment during Cool-off Period) or this drawdown is a preferential product as stipulated in Section 13 of these Terms & Conditions, its original number of installments as originally stated in the Application Form relating to this drawdown shall be counted for the purposes of determining any overlap with other drawdowns (even if such other drawdowns were disbursed after the actual complete repayment of such drawdown).<br>'
    . '(3) Cancelation of Flexibility Package for a drawdown must be made before the due date of its last installment and the paid-up Flexibility Package Fee will not be refunded even when none of the Flexibility Package services has been used. Cancelation may not be made if the Borrower once used even one of the Flexibility Package services. When the drawdown for which the Borrower applies to cancel Flexibility Package is an overlapping drawdown, if the loan period of other drawdowns which overlap with this drawdown has already expired while filing the application, then the Flexibility Package of this drawdown may be cancelled only when the Borrower has not yet used one of Flexibility Package services during the loan period of this drawdown. If the loan period of other drawdowns which overlap with this drawdown has not yet expired while filing the application, then the Borrower can only apply to cancel Flexibility Packages for all such overlapping drawdowns, however, if one of Flexibility Package services under any one of the overlapping drawdowns has been used, then no cancelation of Flexibility Packages shall be available for all such overlapping drawdowns.<br>',
    '__terms2P23__'         => '5.2 Payment Holiday:<br>'
    . '(1) The Borrower is allowed to apply for Payment Holiday only after the Borrower has already fully repaid at least 5 monthly installments for a drawdown under this Contract on schedule; The Borrower can only use Payment Holiday one time at most per each application. The installment number for each Payment Holiday is at least one installment and at most two installments. In case that the Borrower intends to apply for Payment Holiday again after using Payment Holiday, he/she shall repay at least 2 monthly installments in full after he/she uses Payment Holiday the last time.<br>'
    . '(2) In case that the Borrower has overlapping drawdowns under this Contract when applying for usage of Payment Holiday, then the application for Payment Holiday each time shall apply to each one of such overlapping drawdowns whose loan period has not yet expired, provided that he/she has already fully repaid at least 5 monthly installments for one of such overlapping drawdowns on schedule.<br>'
    . '(3) No interest, Loan Administration Fee, Handling Fee (if any), Flexibility Package Fee and Customer Service Fee under this Contract will be charged during the Payment Holiday.<br>'
    . '(4) Each time when the Borrower applies for Payment Holiday, the Lender shall be entitled to decline the application if the Lender reasonably believes that the circumstances of the Borrower cannot satisfy its requirement on risk management and/or increase the probability of the Borrower’s default.',
    '__terms2P24__'         => '5.3 Change of Due Date:<br>'
    . ' (1)  The Change of Due Date applies to all drawdowns hereunder.<br>'
    . '(2)  The Borrower may apply for changing the due date after repaying at least one installment in full on schedule for each drawdown; In case that the Borrower applies for changing the due date again after changing the due date, he/she shall repay at least one monthly installment in full on schedule after his previous change of the due date.<br>'
    . '(3) If the Borrower has any loan(s) outstanding other than those under this Contract and where the Customer Service Provider for such loan(s) is the same customer service provider hereunder, the application for the Change of Due Date hereunder applies to all such other outstanding loans. If the Borrower intends to change the due date based on a different contract again after he/she has changed the due date based on this Contract or other contracts, he/she can apply only after the first changed due date.',
    '__terms2P25__'         => '5.4 Maximum Usage times for Payment Holiday and Change of Due Date<br>'
    . '(1) The maximum usage times for Payment Holiday and Change of Due Date of each drawdown is as follows: for the drawdown of no more than 12 installments (including 12 installments) is one time respectively; for the drawdown of more than 12 installments and no more than 24 installments (including 24 installments) is respectively two times accumulatively; for the drawdown of more than 24 installments and no more than 36 installments (including 36 installments) is respectively three times accumulatively; for the drawdown of more than 36 installments and no more than 48 installments (including 48 installments) is respectively four times accumulatively; for the drawdown of more than 48 installments and no more than 60 installments (including 60 installments) is respectively five times accumulatively; and for the drawdown of more than 60 installments is respectively six times accumulatively.<br>'
    . '(2) The maximum installment number for Payment Holiday of each drawdown is as follows: for the drawdown of no more than 12 installments (including 12 installments) is one installment; for the drawdown of more than 12 installments and no more than 24 installments (including 24 installments) is two installments accumulatively; for the drawdown of more than 24 installments and no more than 36 installments (including 36 installments) is three installments accumulatively; for the drawdown of more than 36 installments and no more than 48 installments (including 48 installments) is four installments accumulatively; for the drawdown of more than 48 installments and no more than 60 installments (including 60 installments) is five installments accumulatively; and for the drawdown of more than 60 installments is  six installments accumulatively. The Borrower may choose one or two installment(s) while applying for Payment Holiday each time. However, the Borrower shall not request using the rest usage times when the maximum installment number is used up.<br>'
    . '(3) If the Borrower has overlapping drawdowns under this Contract and purchased the Flexibility Package for each one of such overlapping drawdowns, such overlapping drawdowns shall be deemed as a single drawdown for the purpose of determining  the maximum usage times of Payment Holiday and Change of Due Date, the maximum installment number for Payment Holiday and usage terms, and the number of installments, the maximum usage times and the maximum installment number of such deemed single drawdown shall be calculated in the following way:<br>'
    . 'a) The number of installments shall be a total sum determined by counting from the first installment of the one of such overlapping drawdowns whose loan period begins at earliest till the last installment of the one of such overlapping drawdowns whose loan period ends at latest and any installments of such overlapping drawdowns with the same Due Date shall be treated as one single installment.<br>'
    . 'b) If a drawdown overlaps respectively with an earlier applied drawdown and a later applied drawdown (while the earlier and the later drawdown do not overlap with each other), this drawdown shall be treated as one single drawdown respectively only with the earlier applied drawdown and then only with a later applied drawdown. The number of installments shall be calculated by counting from the first installment of such drawdown which shall be deemed as a single drawdown with the later applied drawdown. <br>'
    . 'c) If Payment Holiday or Change of Due Date has been used relating to one drawdown before this drawdown overlaps with other drawdown(s), then such previous usage shall be deducted while determining the maximum usage times for Payment Holiday and Change of Due Date and/or the maximum installment number for Payment Holiday after this drawdown overlaps with other drawdown(s) and is treated as one single drawdown.<br>'
    . 'd) If the Institutional Parties change the maximum usage times of Payment Holiday and Change of Due Date and/or the maximum installment number for Payment Holiday as mentioned above in Section 5.4(1) after the Borrower applied a drawdown, then the parameter before the change shall still apply to the drawdowns applied by the Borrower before the change. If drawdowns applied by the Borrower after the change overlap with drawdowns applied by the Borrower before the change, then the principle which parameter is more beneficial to the Borrower shall apply when determining the maximum usage times for Payment Holiday and Change of Due Date and/or the maximum installment number for Payment Holiday applicable to such overlapping drawdowns as deemed a single drawdown.<br>'
    . 'e) An example for calculating the maximum usage times and the maximum installment number for drawdowns which overlap and are treated as one single drawdown: the Borrower applied for one drawdown which has 12 installments. After six months he/she applied for another one drawdown which has 24 installments. Some installments of these two drawdowns overlap and shall be deemed as a single drawdown. The consolidated number of installments in this case is 30 and the maximum usage times for Payment Holiday and Change of Due Date respectively is three times accumulatively and the maximum installment number for Payment Holiday is three installments accumulatively as well.',
    '__terms2P26__'         => '5.5 Free Early Repayment: Free Early Repayment can be applied to some or all drawdowns hereunder. Upon repaying three consecutive monthly installments in full relating to each of the drawdowns intended for early repayment under this Contract, the Borrower may apply for Free Early Repayment relating to such drawdown(s) in accordance with the stipulations of these Terms & Conditions regarding the early repayment, but does not need to pay any Early Repayment Fee additionally.',
    '__terms2P27__'         => '5.6 The Borrower shall file the application for using the Payment Holiday and Free Early Repayment through convenient service channels at least 15 days prior to the next due date. In case of Change of Due Date, the Borrower shall file the application through convenient service channels at least 15 days prior to the first new due date. The Borrower can only apply for one of the Flexibility Package services at a time. The Borrower may apply for another one of the Flexibility Package services after he/she finished using the previously applied Flexibility Package service and paid one monthly installment under this Contract. If Section 5.2, 5.3, 5.4 or 5.5 stipulate higher requirements, such higher requirements shall apply. The Borrower shall not be entitled to use Flexibility Package service in case he/she has any due and unpaid amount or late fee under this Contract with the Lender and/or Customer Service Provider, or although the Borrower was not in default at the time of application, if any default occurs prior to that the first due date after applied payment holiday or applied Change of Due Date or Free Early Repayment takes effect, the application shall become automatically invalid.',
    '__terms2P28__'         => '5.7 The Lender reserves the right to reduce the scope of the flexibility package service or fully deny the flexibility package service with respect to the conditions and risk profile of the Borrower.',
    '__terms2P29__'         => '5.8 Neither late fee is charged nor the Borrower’s credit record is affected for using the flexibility package service.',
    '__terms2H7__'          => '6. CUSTOMER SERVICES',
    '__terms2P30__'         => '6.1 In relation to each drawdown under the Contract, the Customer Service Provider provides the following services to the Borrower:<br>'
    . '(1) Customer advisory service;<br>'
    . '(2) Personal and contact information change management (free of charge);<br>'
    . '(3) Document storage;<Br>'
    . '(4) Document retrieval (free of charge);<br>'
    . '(5) Pay off letter service (free of charge);<br>'
    . '(6) Offering different repayment channels;<br>'
    . '(7) Repayment information inquiry (free of charge);<br>'
    . '(8) Repayment reminder and informing;<br>'
    . '(9) Customer mistakes corrections (free of charge); and<br>'
    . '(10) Over payment handling (free of charge except for the  remittance fees charged by bank for overpayment return).',
    '__terms2P31__'         => '6.2 In consideration for the above services, the Borrower shall pay a fee (the “customer service fee”), which is charged every month during the loan period and forms a part of the monthly installments. Each abovementioned services(excluding the free services) rate is ¼ of the customer service fee rate, and the customer service fee rate is stated as “monthly customer service fee rate” on each one of the Application Forms relating to the respective drawdowns.',
    '__terms2H8__'          => '7. REPAYMENT OF THE LOAN & PAYMENT OF FEES',
    '__terms2P32__'         => '7.1 If the Borrower does not choose direct debit on the Application Form, the Borrower shall deposit every monthly installment into the bank account designated by the Lender provided on the Application Form (the “repayment account”) on the due date. The date when a Borrower’s payment is deemed made hereunder is the date when the funds arrive on the repayment account. Therefore, the Borrower should consider transferring funds early enough so that it arrives on the repayment account on time.',
    '__terms2P33__'         => '7.2 If the Borrower chooses direct debit on the Application Form, the Borrower hereby irrevocably authorizes the Institutional Parties to direct debit, from the Borrower’s bank account provided on the Application Form, the due monthly installment and all other amounts due and owing hereunder, without further notice to or consent from the Borrower. Direct debit will take place no earlier than the due date. Borrower shall keep enough amount during the whole day of the due date. Failure of any direct debit attempt in connection with this Contract, regardless of the reason, does not diminish the Borrower’s obligation hereunder to make payment and the Borrower shall make payment by any reasonable means.',
    '__terms2P34__'         => '7.3 If for the convenience of the Borrower, the Institutional Parties accept request from the Borrower to direct debit the down payment amount from the Borrower’s bank account when the Borrower applies for a POS loan, then the Borrower authorizes the Institutional Parties to direct debit the down payment payable to the Merchant from the Borrower’s account as stated on the Application Form relating to this drawdown and transfer the down payment to the Merchant. In case of failure of any direct debit attempt with respect to the down payment for whatever reason, the application of that drawdown will become invalid automatically.',
    '__terms2P35__'         => '7.4<br>'
    . '(1) If the Borrower chooses direct debit on the Application Form of the latest drawdown hereunder, the Borrower hereby consents to authorizing direct debit for all drawdowns hereunder and for all his/her other loans outstanding where the customer service provider is the same as hereunder and the bank account under the Borrower’s latest authorization will prevail.<br>'
    . '(2) If the Borrower does not choose direct debit on the Application Form of the latest drawdown hereunder, the Borrower hereby consents to canceling direct debit for all drawdowns hereunder where direct debit was already authorized and under his/her other loans outstanding where the customer service provider is the same as hereunder.<br>'
    . '(3) If the Borrower provides a different bank account in his/her latest Application Form for the latest drawdown under this Contract, such bank account shall be used for direct debit of all payments relating to all outstanding drawdowns hereunder and to his/her other loans outstanding where the customer service provider is the same as hereunder.<br>'
    . '(4) The Borrower may change direct debit through the convenient service channels. This change will automatically apply to all drawdowns under this Contract and to his/her other loans outstanding where the customer service provider is the same as hereunder.',
    '__terms2P36__'         => '7.5 For some drawdowns only direct debit will be available based on the decision of the institutional Parties.',
    '__terms2P37__'         => '7.6 No clause in this Section 7 shall diminish the obligation of the Borrower to pay other amounts hereunder such as late fees.',
    '__terms2P38__'         => '7.7 The Customer Service Provider authorizes the Lender to collect the customer service fee and handling fee (if any) from the Borrower and pay it to Customer Service Provider.',
    '__terms2P39__'         => '7.8 Payments to the repayment account are applied to the receivables categories below in the following sequence (including the circumstance where the Borrower took out multiple consumer finance loans where the Customer Service Provider is the customer service provider thereunder):<br>'
    . '(1) Any debt that becomes due at the earliest time shall be repaid first.<br>'
    . '(2) Amongst the debts that become due simultaneously, monthly installment amounts are repaid before late fees.<br>'
    . '(3) Amongst monthly installment amounts that become due simultaneously, the one relating to the contract that was signed earliest shall be repaid first.<br>'
    . '(4) Among drawdowns under this Contract, the one withdrawn first shall be repaid first.<br>'
    . '(5) Payments are applied in the following order to a monthly installment amount: principal, interest, stamp duty, loan administration fee, customer service fee, handling fee (if any) and flexibility package fee (if any).<br>'
    . '(6) Amongst multiple consumer finance loans or multiple drawdowns under this Contract applied by the Borrower with the same due date, the one where early repayment has been applied for shall be repaid first.',
    '__terms2P40__'         => '7.9 The Borrower is responsible for retaining the proof of his/her payments hereunder. If the Borrower’s repayment is in controversy, the Borrower is responsible for producing proof of his/her payment.',
    '__terms2H9__'          => '8. LATE FEE FOR LATE PAYMENT',
    '__terms2P41__'         => '8.1 If the Borrower breaches any payment obligation hereunder, he/she shall make up the due and unpaid amount immediately together with late fees generated pursuant to this Section. Late fees are generated separately for each drawdown based on the time period elapsed since the earliest monthly installment that was not paid in full for that drawdown – i.e. number of days past due.',
    '__terms2P42__'         => '8.2 On the tenth day past due, RMB 30 late fee is generated. On the thirtieth day past due, an additional RMB 80 late fee is generated. On the sixtieth day past due, an additional RMB 130 late fee is generated. On the ninetieth day past due, an additional RMB 130 late fee is generated.',
    '__terms2P43__'         => '8.3 If the loan principal of single drawdown is below 1000 RMB, the late fees with respect to that drawdown will be halved according to Section 8.1 and 8.2.',
    '__terms2P44__'         => '8.4 When a Borrower who is in default makes payment, the funds will be applied to his/her due and owing amounts, and his/her number of days past due may be reduced. However, if not all of the due and owing amounts are repaid, the number of days past due will continue to increase and when they reach the time periods specified in above again, more late fee will be imposed.',
    '__terms2H10__'         => '9. EARLY REPAYMENT OPTION',
    '__terms2P45__'         => '9.1 The Borrower may discharge one or all of his/her drawdowns through early repayment. Early repayment involves paying in one lump sum (the “ER amount”) on or before the due date of a particular month (the “ER month”):<br>'
    . '(1) The customer service fee, loan administration fee, handling fee (if any), flexibility package fee (if any) and interest arising from the respective drawdown(s) that ordinarily would become due on the due date of the ER month. In case other drawdowns are outstanding and are not part of early repayment in question, flexibility package fee shall continue to be paid as part of monthly installments on those drawdowns;<br>'
    . '(2) All remaining principal of the respective drawdown(s), whether due on the due date of the ER month or thereafter; and<br>'
    . '(3) Early repayment fee of RMB 200 per each early repaid drawdown paid to Lender (except for the circumstances as stipulated under Section 5.5 and 9.4 as well as circumstances under which the Borrower early repays drawdown(s) applied through HCC Gateway).',
    '__terms2P46__'         => '9.2 Application for early repayment is made through the convenient service channels by at least 15 days prior to the ER month’s due date authorizing and requesting the Customer Service Provider to carry out early repayment formalities with the Lender on Borrower’s behalf. The Institutional Parties will inform the Borrower the specific ER amount through convenient service channels.',
    '__terms2P47__'         => '9.3 The ER amount is payable in the same manner as the regular monthly installment and the same rules in Section 7 apply. However, the direct debit for ER amount may take place earlier than the due date.',
    '__terms2P48__'         => '9.4 Cool-off Period: If, within 15 days from signing or submitting through the convenient service channels or authorizing Customer Service Provider to submit the Application Form of one drawdown (including the signing date or submission date), the Borrower applies for early repayment and the full amount of principal of that drawdown is credited to the repayment account, the Institutional Parties will charge no interest and no fees with respect to the drawdown(s) so repaid.',
    '__terms2P49__'         => '9.5 Except for section 9.4, early repayment is possible only if the Borrower has no outstanding overdue amounts or unpaid late fees hereunder or under any contract where the Customer Service Provider is the customer service provider thereunder. If the Borrower becomes delinquent under any of the foregoing contracts before the ER month due date, any early repayment is automatically canceled.',
    '__terms2P50__'         => '9.6 If the Borrower cancels the purchase order or returns the Product to the Merchant within 30 days from the submission date for the respective drawdown applied through HCC Gateway (including the submission date), then, that drawdown will be automatically cancelled upon confirmation between the Lender and the Merchant about the order cancellation or return of Product and the Institutional Parties will return to the Borrower without undue delay all amounts of monthly installments (if any) in full with respect to that drawdown that were already paid by the Borrower. No fees will be charged by the Institutional Parties with respect to the above; If the Borrower cancels the purchase order or return the Product to the Merchant after 30 days from the submission date for the respective drawdown applied through HCC Gateway, then that drawdown will be automatically cancelled upon confirmation between the Lender and the Merchant about the order cancellation or return of Product and the Institutional Parties will return to the Borrower without undue delay the part of monthly installments that were already paid by the Borrower (if any) with respect to that drawdown representing the repayment of the principal of that drawdown. Interest and fees will not be returned. Section 9.6 is applicable only for full cancellation of purchase order or full return of Product relating to the respective drawdown applied by the Borrower through HCC Gateway.<br>'
    . 'The Institutional Parties reserve the right to set-off any amounts to be returned under the above clause against any overdue amounts payable by the Borrower hereunder. In case of any controversy over timing of the above return of Product or cancellation of purchase order, the records of Institutional Parties shall prevail.',
    '__terms2H11__'         => '10. USE OF CONVENIENT SERVICE CHANNELS',
    '__terms2P51__'         => '10.1	The Institutional Parties and the Borrower can use convenient service channels to make application for additional drawdowns and approve applications, to make changes to this Contract and communication related to loan. Convenient service channels include HCC Gateway, telephone, online customer portal, SMS and other technical means such as mobile app etc. made available by the Institutional Parties. However, the Institutional Parties do not guarantee the availability of all convenient service channels or all the functions at all times to the Borrower.<br>'
    . 'The Borrower shall follow the requirements of the Contract and relevant business rules etc. published occasionally by the Institutional Parties through POS, website or convenient service channels when enjoying the service provided by the Institutional Parties. The Borrower agrees to use convenient service channels in line with their respective terms of use published occasionally by the Institutional Parties such as Terms of Use regarding HCC Gateway and Terms of Use regarding Online Customer Portal. The Institutional Parties shall be entitled to amending and/or supplementing this Contract and terms of use any time through convenient service channels.',
    '__terms2P52__'         => '10.2 The Borrower shall guarantee the genuineness, completeness, validity of its personal information. If any changes, the Borrower shall notify the Institutional Parties according to this Contract and handle modification formalities upon the Institutional Parties’ request. The Borrower may modify its personal information through the convenient service channels if such function is available. Any risk, loss and liability incurred due to falsity, incorrectness, incompleteness etc. of the personal information of the Borrower shall be borne by the Borrower.',
    '__terms2P53__'         => '10.3 Identity authentication factor refers to the factor which the Institutional Parties and the Borrower agree to use in the convenient service channels in order to verify the identity of the Borrower, such as customer number (user name, identity number etc.), password, electronic certificate, dynamic password, calling number set up during the contract concluding, bank account number, phone number registered with the issuing bank, Email address, etc. The Borrower irrevocably agrees that any transaction by using his/her identity authentication factor shall be deemed as conducted by the Borrower him/herself. The Borrower agrees that he/she will bear results incurred and shall be liable for all damages, obligations and payments arising from the use of his/her identity authentication factor irrespective of who actually used it.',
    '__terms2P54__'         => '10.4 The Borrower shall keep his/her identity authentication factors safe and shall not disclose any of them to any third party. If the identity authentication factor of the Borrower is lost, stolen, forgotten or suspected to be known to or misused by a third party and it could result in the decrease in safety of the Borrower’s use of convenient service channels, the Borrower shall be obligated to immediately report to Institutional Parties and change the identity authentication factor in accordance with the method as informed by the Institutional Parties. The Borrower agrees to bear all losses and liabilities incurred when he/she fails to fulfill the aforementioned obligations in a timely manner.',
    '__terms2P55__'         => '10.5 The Borrower shall perform the duty of reasonable care and use the convenient service channels in a safe environment. ',
    '__terms2H12__'         => '11. REPRESENTATIONS AND WARRANTIES',
    '__terms2P56__'         => '11.1 The Borrower represents to the Institutional Parties that:<br>'
    . '(1) All information provided by the Borrower for the purpose of the Contract (including Product information) is complete, accurate, authentic and not misleading.<br>'
    . '(2) There are no circumstances whatsoever existing that might affect the Borrower’s creditworthiness, such as involvement in any legal action, arbitration or administrative proceeding in whatever manner or form, whether in process or threatened.<br>'
    . 'The Borrower shall fully indemnify the Institutional Parties against any losses of any kind arising from a breach of or inaccuracy in the Borrower’s representations.',
    '__terms2P57__'         => '11.2 The Borrower undertakes to only use the loan for personal consumption purpose rather than using the loan for speculation in equity capital investment, securities, or illegal activities prohibited by relevant laws and regulations.',
    '__terms2P58__'         => '11.3 The Borrower shall proactively cooperate with the Institutional Parties in relation to their supervision of the Borrower’s credit standing, use of the loan and repayment. The Borrower undertakes to provide relevant consumption proof (including but not limited to consumption invoices, contracts, etc.) for examination of the use of the loan stated on the Application Form according to the Institutional Parties’ request at any time. If the identity authentication factor is compromised, the Borrower shall proactively cooperate with the Institutional Parties in relation to further verification. The Borrower shall provide additional documents and information or even show up in person upon request by the Institutional Parties if necessary.',
    '__terms2P59__'         => '11.4 The Borrower hereby irrevocably authorizes the Institutional Parties to take following actions:<br>'
    . '(1) to enquire and obtain his/her personal information, his/her personal credit-related information and any other information (including bad credit record, if any) reflecting his/her credit status from and provide the abovementioned information to the PBOC Individual Credit Information Database from the concluding of the Contract throughout the whole loan life.<br>'
    . '(2) out of the need for providing the loan, to provide his/her personal information and related loan information to domestic affiliated companies and business partners involved in the consumer finance business, includes but not limited to processing loan applications, managing  all stages of the loan, managing accounts and payments, protection and enforcement of rights etc.<br>'
    . '(3) to outsource part of the services related to the Contract to its business partners and provide his/her related personal information to such partners in this respect.<br>'
    . '(4) out of the need for providing the loan, to enquire and obtain his/her related personal information (including but not limited to the Borrower’s identity information, social security information and housing fund information, etc.) from the Lender’s domestic affiliated companies and business partners and other lawful available sources.<br>'
    . '(5) to obtain all details and information/data concerning the Borrower which are available in any third party irrespective whether the Borrower has given his/her consent to such third party to share such his/her data with any third person. The Borrower hereby authorizes all parties in lawful possession of data about the Borrower (without limitation) to provide information/data or enable access to their data and to share such data with the Institutional Parties for the purposes of evaluation of his/her credit status and for other purposes related to the issuance/repayment/enforcement of the loan applied for hereunder.<br>'
    . '(6) to take advantage of his/her personal information to recommend products, including sending commercial advertisement to his/her postal address, e-mail address, mobile phone, QQ, Wechat, APP etc., which shall still be effective after the Contract expires.<br>'
    . '(7) to properly keep all the personal and credit information and documents provided by it and use them within the scope of the above authorizations.<br>'
    . '(8) to exchange personal and credit information with the merchants and other third parties in relation to processing payment for Borrower’s purchase of Products with loans hereunder.',
    '__terms2P60__'         => '11.5 In case of a breach of this Contract by the Borrower, the Borrower irrevocably consents to the Institutional Parties (or any third-party they may engage) reminding the Borrower about such breach and urging the Borrower to remedy such breach in person or by phone call, post, internet or any other method in accordance with the law, whether directly or through a third-party who may know the Borrower and, for the purpose of so doing, to disclose the Borrower’s breach of this Contract to such third-party.',
    '__terms2P61__'         => '11.6 The Borrower acknowledges that the contractual relationship arising from this Contract and the contractual relationship between the Borrower and the Merchant or any third party are separate and distinct. The effectiveness of the Contract is not affected by any invalidity of or change to the contractual relationship between the Borrower and the Merchant. In this connection, any dispute (including but not limited to disputes over Product quality or after-sale services) between the Borrower and the Merchant or any other third-party while using loans for consumption by the Borrower is not a reason for refusing to perform any obligation hereunder.',
    '__terms2P62__'         => "11.7 The Borrower shall notify the Customer Service Provider within five days of any change to the Borrower’s information as set forth on the Application Form, any material changes to the Borrower's personal assets and financial standing and any other matter that may affect the performance of his/her obligations hereunder.",
    '__terms2H13__'         => '12. ACCELERATION',
    '__terms2P63__'         => '12.1 Upon any of the following events, the Lender is entitled to demand the Borrower pay all amounts under this Contract in one lump sum immediately:<br>'
    . '(1) The Borrower breaches any obligation hereunder;<br>'
    . '(2) The Borrower materially breaches any other loan contract entered into with the Lender or another lender;<br>'
    . '(3) Any of the Institutional Parties strongly suspects that the Borrower has conducted any fraudulent act in relation to the loan or the customer service fee or that the Borrower may not have the ability to make payments in accordance with the Contract; and<br>'
    . '(4) Any other circumstances of the Borrower that in the reasonable judgment of any of the Institutional Parties might adversely affect any Institutional Party’s rights or interests such as including but not limited to that the Institutional Parties fail to contact the Borrower.',
    '__terms2P64__'         => '12.2 If any of the above events occur before the Lender disburses the funds for the first drawdown, the Institutional Parties may terminate the Contract without any disbursement or further obligation. If any of the above events occur before the Lender disburses the funds for any subsequently requested drawdowns, the Lender reserves the right to (1) cancel the disbursement for each undisbursed drawdown at its discretion without giving reasons and/or (2) terminate the Contract which results in (3) the Borrower’s obligation to repay all amounts under this Contract in one lump sum immediately. The Institutional Parties will inform the Borrower of such termination or cancellation.',
    '__terms2P65__'         => '12.3 If the Borrower fails to fully pay any installment with respect to any drawdown 90 days after its due date, the loan period for all drawdowns will automatically terminate, and the Borrower shall pay all amounts due under this Contract in one lump sum immediately.',
    '__terms2P66__'         => '12.4 If the Borrower has other loan(s) outstanding apart from this Contract where the Customer Service Provider is the customer service provider for such loan, the acceleration of any other loan(s) will cause the Lender to accelerate all drawdowns under this Contract.',
    '__terms2H14__'         => '13. PROMOTION',
    '__terms2P67__'         => '13.1 The Preferential Product provided by the Institutional Parties during series sales promotion events conforms to the “Product Code” as stated on the Application Form of each drawdown. If Product Code contains the word “GIFT”, Section 13.2 and 13.3 shall apply; If Product Code contains the word “TENTHER”, Section 13.4 and 13.5 shall apply.',
    '__terms2P68__'         => '13.2 If the Borrower meets the conditions defined in Section 13.3 of the Contract, the Institutional Parties shall grant him/her (1) waiver of the loan administration fee, customer service fee, interest, handling fee (if any) and flexibility package fee (if any) part of the last installment of such drawdown(s) and (2) discount on the previously paid loan administration fee, customer service fee and interest part of the previously paid installments equal to the amount of the loan principal part in the last installment of such drawdown(s) payable according to the customer repayment calendar on that drawdown under the Contract. The amount of the granted discount as per (2) above will be applied by the Institutional Parties to settle the loan principal part of the last installment of such drawdown(s) otherwise payable by the Borrower.',
    '__terms2P69__'         => '13.3 Promotion eligibility criteria:<br>'
    . '(1) The Borrower does not make early repayment with respect to such drawdown(s) (including free early repayment);<br>'
    . '(2) The Borrower has paid all installments except last installment of such drawdown(s) on time, duly and fully in compliance with this Contract;<br>'
    . '(3) The Borrower maintains valid and up-to-date contact information including his/her mobile phone number with Customer Service Provider; and<br>'
    . '(4) There is no overdue amount with respect to any drawdown under the Contract.',
    '__terms2P70__'         => '13.4 If the Borrower makes timely and full repayment of the first four installments of such drawdown(s) as provided by the Contract, and also makes extra repayment of an amount which equals to the balance of loan principal minus the sum of first four installments of such drawdown(s) (excluding handling fee and flexibility package fee, if any) at same time of or prior to making repayment of the fourth installment, the Borrower shall only be obliged to repay the loan principle and handling fees (if any) and flexibility package fees (if any) contained in first four installments of such drawdown(s). The Institutional Parties shall give him/her a waiver of and meantime use the loan administration fees, customer service fees and interests contained in the first four installments of such drawdown(s) already repaid by the Borrower to settle the outstanding part of the loan principal of such drawdown(s) payable by the Borrower, and deem the Borrower pays off all payables of such drawdown(s). The Borrower shall meet the conditions defined in Section 13.5 for being eligible for the waiver herein.  ',
    '__terms2P71__'         => '13.5	Promotion eligibility criteria:<br>'
    . '(1) The Borrower does not make early repayment with respect to such drawdown(s) (including free early repayment);<br>'
    . '(2) The Borrower files an application prior to the due date for the fourth installment of such drawdown(s) by calling the Customer Service Provider, and makes repayment of the amount as instructed by the Customer Service Provider;<br>'
    . '(3) The Borrower maintains valid and up-to-date contact information including his/her mobile phone number with Customer Service Provider; and<br>'
    . '(4) There is no overdue amount with respect to any drawdown under the Contract.',
    '__terms2P72__'         => '13.6 In case of any doubt, the Institutional Parties’ records on fulfillment of conditions defined in Section 13.3, 13.4 and 13.5 of the Contract will be used for reference and decision on eligibility. In no circumstances, would the Borrower’s credit record be affected by the waiver and discount.',
    '__terms2H15__'         => '14. DISPUTE RESOLUTION',
    '__terms2P73__'         => '14.1 Any dispute arising from or in connection with the Contract shall be resolved by negotiation. If negotiation cannot resolve the dispute, any party may initiate a legal action in a People’s Court located in the jurisdiction where the Contract is deemed concluded. (Please view the stipulations on the signing place in the bottom left of the Consumer Finance Loan Contact, Terms & Conditions.) The losing party agrees to pay court fees, legal fees, notary fees, transportation fees and all other costs incurred by the other parties in relation to the entire dispute resolution process.',
    '__terms2P74__'         => '14.2 While a dispute is in the process of resolution, all parties hereto shall continue to perform their obligations hereunder.',
    '__terms2H16__'         => '15. MISCELLANEOUS',
    '__terms2P75__'         => '15.1 If any provision of the Contract is declared by any judicial or other competent authority to be invalid, the parties agree that the validity of the remaining provisions will not be affected thereby.',
    '__terms2P76__'         => '15.2 All the Parties agree that the Contract may be signed only once and the fully signed original Contract shall belong to the Lender. Customer Service Provider shall keep a copy of the Contract for the Borrower and itself, and the copy of Contract has the same legal effect as the original one, The Borrower hereby irrevocably authorizes the Customer Service Provider to keep custody of his/her copy of the Contract for safekeeping and consents to the Customer Service Provider discarding it after all drawdowns are fully repaid.',
    '__terms2P77__'         => '15.3 To avoid the inconvenience of receiving notices, the Borrower hereby irrevocably consents to the Institutional Parties, at their sole discretion, transferring their receivables hereunder to a third-party without notice to the Borrower if the manner of payment expected by the Borrower remains unchanged.',
    '__terms2P78__'         => '15.4 To avoid the unnecessary burden of lawsuits to all parties involved, the Borrower irrevocably agrees that in case of any default of repayment by the Borrower, the Lender can at its sole discretion decide to pay the amount payable by the Borrower to the Customer Service Provider on behalf of the Borrower  without additional notice to the Borrower. The Lender shall be entitled to claim for the amount it pays representing the Borrower by means of litigation etc.',
    '__terms2P79__'         => '15.5 The Borrower understands and consents to each monthly installment being calculated as the sum of (1) to (5) below, if the Borrower shall repay two or more drawdowns on one due date, then the monthly installment to be paid by the Borrower on that due date shall be the summation of the monthly installments of the aforementioned drawdowns, where Yuan is the smallest unit:<br>'
    . '(1) principal and interest relating to that particular month repaid by means of monthly installments composing of both principal and interest of equal amounts, where the interest is calculated as the unpaid principal of that drawdown multiplied by the monthly interest rate as stated on the Application Form relating to that drawdown;<br>'
    . '(2) the loan administration fee relating to that particular month, calculated as the full principal of that drawdown multiplied by the monthly loan administration fee rate provided on the Application Form relating to that drawdown;<br>'
    . '(3) the customer service fee relating to that particular month, calculated as the full principal of that drawdown multiplied by the monthly customer service fee rate provided on the Application Form relating to that drawdown;<br>'
    . '(4) the handling fee relating to that particular month as provided by “monthly handling fee” on the Application Form of that drawdown.<br>'
    . '(5) the flexibility  package fee relating to that particular month as provided by “monthly flexibility package fee” on the Application Form of that drawdown.<br>'
    . 'Stamp duty arising from the Contract taxable from the Borrower is paid to tax authorities by the Lender on behalf of the Borrower. The stamp duty is calculated and included in the first monthly installment.',
    '__terms2P80__'         => '15.6 This Contract remains in force even after all drawdowns are fully repaid.',
    '__terms2P81__'         => 'Lender: Home Credit Consumer Finance Co., Ltd.<br>
Customer Service Provider: Shenzhen Home Credit Financial Service Co., Ltd.<br>
Borrower:<br>
Version Number: T&C_CFC_20150716<br>
Deemed contracting location of drawdowns applied under HCC Gateway is the registered address of branch office of the Customer Service Provider in the provincial capital of the province where the Borrower’s bank account number stated in his/her Application Form indicates. If there is no branch office registered by the Customer Service Provider in the provincial capital of the province where the Borrower’s bank account number indicates, then the deemed contracting location is the register address of head office of the Customer Service Provider in Shenzhen. Deemed contracting location of  drawdowns applied through other ways is the registered address of branch offices of the Customer Service Provider in the provincial capital of each province with an exception that the deemed contracting location is within Guangdong Province. In this case the deemed contracting location is the register address of head office of the Customer Service Provider in Shenzhen. If Borrower has multiple drawdowns under the same Contract, the deemed contracting location of his/her first drawdown shall prevail.',  
        );